
package p3tarea3grupo3.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.bson.Document;
import p3tarea3grupo3.controller.Account;
import p3tarea3grupo3.controller.ListClient;
import p3tarea3grupo3.controller.designpattern.decorater.Authenticate;
import p3tarea3grupo3.controller.designpattern.decorater.AuthenticateUser;

public class LPanelUser extends javax.swing.JPanel {
    
    Authenticate authenticate;
    ListClient client;
    List<Account> listAccount;
    Account userBanck;
    
    public LPanelUser() {
        initComponents();
        
        authenticate = new AuthenticateUser();
        client = ListClient.getInstance();
        listAccount = client.getAccount();
        
        this.lblNotVisible.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUser = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlUser = new ComponentRoundJilmar.PanelRound();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        pnlPassword = new ComponentRoundJilmar.PanelRound();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        lblVisible = new javax.swing.JLabel();
        lblNotVisible = new javax.swing.JLabel();
        lblRecovery = new javax.swing.JLabel();
        btnRegister = new ComponentRoundJilmar.LabelRound();
        btnLogin = new ComponentRoundJilmar.LabelRound();
        wallpaper = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new Color(0,0,0,0));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 210, 20));

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("Usuario:");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 40)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("BANCA VIRTUAL");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        lblSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setText("Ingresa con tu usuario y contraseña");
        jPanel1.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setRoundBottomLeft(50);
        pnlUser.setRoundBottomRight(50);
        pnlUser.setRoundTopLeft(50);
        pnlUser.setRoundTopRight(50);
        pnlUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtUser.setText("jigonzalez3");
        txtUser.setBorder(null);
        pnlUser.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/user.png"))); // NOI18N
        pnlUser.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jPanel1.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 460, 50));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        pnlPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlPassword.setRoundBottomLeft(50);
        pnlPassword.setRoundBottomRight(50);
        pnlPassword.setRoundTopLeft(50);
        pnlPassword.setRoundTopRight(50);
        pnlPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        txtPassword.setText("010302");
        txtPassword.setBorder(null);
        pnlPassword.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 330, 28));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/password.png"))); // NOI18N
        pnlPassword.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/visible1.png"))); // NOI18N
        lblVisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVisibleMouseClicked(evt);
            }
        });
        pnlPassword.add(lblVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        lblNotVisible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/notVisible1.png"))); // NOI18N
        lblNotVisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotVisibleMouseClicked(evt);
            }
        });
        pnlPassword.add(lblNotVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, 30));

        jPanel1.add(pnlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 460, 50));

        lblRecovery.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRecovery.setForeground(new java.awt.Color(255, 255, 255));
        lblRecovery.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecovery.setText("Olvido su usuario y/o contraseña?");
        jPanel1.add(lblRecovery, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        btnRegister.setBackground(new java.awt.Color(0, 0, 0));
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegister.setText("Registrarse");
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegister.setMaximumSize(new java.awt.Dimension(69, 16));
        btnRegister.setMinimumSize(new java.awt.Dimension(69, 16));
        btnRegister.setPreferredSize(new java.awt.Dimension(69, 16));
        btnRegister.setRoundBottomLeft(50);
        btnRegister.setRoundBottomRight(50);
        btnRegister.setRoundTopLeft(50);
        btnRegister.setRoundTopRight(50);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, 200, 60));

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("Ingresar");
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setRoundBottomLeft(50);
        btnLogin.setRoundBottomRight(50);
        btnLogin.setRoundTopLeft(50);
        btnLogin.setRoundTopRight(50);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, 200, 60));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 670));

        wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/wallpaper.png"))); // NOI18N
        add(wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void lblVisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisibleMouseClicked
        lblVisible.setVisible(false);
        lblNotVisible.setVisible(true);
        txtPassword.setEchoChar((char)0);
    }//GEN-LAST:event_lblVisibleMouseClicked

    private void lblNotVisibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotVisibleMouseClicked
        lblVisible.setVisible(true);
        lblNotVisible.setVisible(false);
        txtPassword.setEchoChar('●');
    }//GEN-LAST:event_lblNotVisibleMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        String userText = txtUser.getText();
        String passText = String.valueOf(txtPassword.getPassword());
        if(authenticate.getAuthenticate(userText, passText)) {
            for (Account a : listAccount) {
                if(a.getPassword().equals(passText) && a.getUser().equals(userText)) {
                    userBanck = a;
                    break;
                }
            }
            MainWindows main = new MainWindows(userBanck);
            main.setVisible(true);
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(LPanelUser.this);
            frame.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "El usuario o contraseño es incorrecto", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        RegisterWindows register = new RegisterWindows();
        register.setVisible(true);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(LPanelUser.this);
        frame.dispose();
    }//GEN-LAST:event_btnRegisterMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.LabelRound btnLogin;
    private ComponentRoundJilmar.LabelRound btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblNotVisible;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRecovery;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblVisible;
    private ComponentRoundJilmar.PanelRound pnlPassword;
    private ComponentRoundJilmar.PanelRound pnlUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel wallpaper;
    // End of variables declaration//GEN-END:variables
}
