
package p3tarea3grupo3.view;

import java.awt.Color;

public class LPanelWelcome extends javax.swing.JPanel {

    private LoginWindows windows;
    
    public LPanelWelcome(LoginWindows windows) {
        initComponents();
        this.windows = windows;
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panelPin = new ComponentRoundJilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelUser = new ComponentRoundJilmar.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblRegister = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbImage = new javax.swing.JLabel();
        panelLine = new javax.swing.JPanel();
        lbFound = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setOpaque(false);
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelPin.setBackground(new java.awt.Color(0, 0, 0));
        panelPin.setPreferredSize(new java.awt.Dimension(180, 120));
        panelPin.setRoundBottomLeft(30);
        panelPin.setRoundBottomRight(30);
        panelPin.setRoundTopLeft(30);
        panelPin.setRoundTopRight(30);
        panelPin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelPinMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PIN");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/pin.png"))); // NOI18N

        javax.swing.GroupLayout panelPinLayout = new javax.swing.GroupLayout(panelPin);
        panelPin.setLayout(panelPinLayout);
        panelPinLayout.setHorizontalGroup(
            panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPinLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        panelPinLayout.setVerticalGroup(
            panelPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPinLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21))
        );

        mainPanel.add(panelPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        panelUser.setBackground(new java.awt.Color(0, 0, 0));
        panelUser.setRoundBottomLeft(30);
        panelUser.setRoundBottomRight(30);
        panelUser.setRoundTopLeft(30);
        panelUser.setRoundTopRight(30);
        panelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUserMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario y Constraseña");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/user_1.png"))); // NOI18N

        javax.swing.GroupLayout panelUserLayout = new javax.swing.GroupLayout(panelUser);
        panelUser.setLayout(panelUserLayout);
        panelUserLayout.setHorizontalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUserLayout.createSequentialGroup()
                .addGroup(panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(panelUserLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelUserLayout.setVerticalGroup(
            panelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        mainPanel.add(panelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 180, 120));

        lblRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRegister.setForeground(new java.awt.Color(255, 255, 255));
        lblRegister.setText("Registrarse");
        lblRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRegisterMouseExited(evt);
            }
        });
        mainPanel.add(lblRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 620, 80, -1));

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Bienvenido a tu Banca Virtual");
        mainPanel.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        lbImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/InitOriginal.png"))); // NOI18N
        mainPanel.add(lbImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 430));

        panelLine.setPreferredSize(new java.awt.Dimension(100, 2));
        panelLine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLineMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLineLayout = new javax.swing.GroupLayout(panelLine);
        panelLine.setLayout(panelLineLayout);
        panelLineLayout.setHorizontalGroup(
            panelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLineLayout.setVerticalGroup(
            panelLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        mainPanel.add(panelLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, -1, -1));

        add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 670));

        lbFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/mainFocus.png"))); // NOI18N
        add(lbFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseClicked
        RegisterWindows windows = new RegisterWindows();
        windows.setVisible(true);
    }//GEN-LAST:event_lblRegisterMouseClicked

    private void lblRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseExited

        lblRegister.setForeground(Color.white);
        
    }//GEN-LAST:event_lblRegisterMouseExited

    private void lblRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegisterMouseEntered
 
       lblRegister.setForeground(new Color(164,57,100));

    }//GEN-LAST:event_lblRegisterMouseEntered

    private void panelLineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLineMouseEntered

        panelLine.setBackground(new Color(164,57,100));
        panelLine.repaint();


    }//GEN-LAST:event_panelLineMouseEntered

    private void panelLineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLineMouseExited

        panelLine.setBackground(Color.white);
        panelLine.repaint();


    }//GEN-LAST:event_panelLineMouseExited

    private void panelLineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLineMouseClicked
      
    }//GEN-LAST:event_panelLineMouseClicked

    private void panelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUserMouseClicked
        windows.showPanel(new LPanelUser());
    }//GEN-LAST:event_panelUserMouseClicked

    private void panelPinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelPinMouseClicked
        windows.showPanel(new LPanelPin());
    }//GEN-LAST:event_panelPinMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lbFound;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lblRegister;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel panelLine;
    private ComponentRoundJilmar.PanelRound panelPin;
    private ComponentRoundJilmar.PanelRound panelUser;
    // End of variables declaration//GEN-END:variables
}
