
package p3tarea3grupo3.view;

import java.awt.Color;
import javax.swing.JOptionPane;
import p3tarea3grupo3.controller.Account;
import p3tarea3grupo3.controller.designpattern.factorymethod.Transaction;
import p3tarea3grupo3.controller.designpattern.factorymethod.Withdrawal;


public class MPanelRetreat extends javax.swing.JPanel {

    MainWindows windows;
    Account account;
    Transaction aplication;
    
    public MPanelRetreat() {
        initComponents();
        
    }
    
    public MPanelRetreat(MainWindows windows, Account account) {
        initComponents();
        this.windows = windows;
        this.account = account;
        aplication = new Withdrawal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOne = new javax.swing.JPanel();
        pnlTitle = new ComponentRoundJilmar.PanelRound();
        lbTitle = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        lbReturn = new javax.swing.JLabel();
        btnConfirmRetiro = new ComponentRoundJilmar.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        pnlRetreat = new ComponentRoundJilmar.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        panelRound2 = new ComponentRoundJilmar.PanelRound();
        txtMoney = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lbFound = new javax.swing.JLabel();

        pnlOne.setBackground(new java.awt.Color(255, 255, 255));
        pnlOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setBackground(new Color(255, 255, 255, 123));
        pnlTitle.setRoundBottomLeft(30);
        pnlTitle.setRoundBottomRight(30);
        pnlTitle.setRoundTopLeft(30);
        pnlTitle.setRoundTopRight(30);

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setText("Retiros");

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/nextOne.png"))); // NOI18N

        lbReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/return.png"))); // NOI18N
        lbReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(lbReturn)
                .addGap(16, 16, 16))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlOne.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, 60));

        btnConfirmRetiro.setBackground(new java.awt.Color(51, 0, 102));
        btnConfirmRetiro.setPreferredSize(new java.awt.Dimension(100, 54));
        btnConfirmRetiro.setRoundBottomLeft(30);
        btnConfirmRetiro.setRoundBottomRight(30);
        btnConfirmRetiro.setRoundTopLeft(30);
        btnConfirmRetiro.setRoundTopRight(30);
        btnConfirmRetiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmRetiroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmRetiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmRetiroMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confirmar Retiro");

        javax.swing.GroupLayout btnConfirmRetiroLayout = new javax.swing.GroupLayout(btnConfirmRetiro);
        btnConfirmRetiro.setLayout(btnConfirmRetiroLayout);
        btnConfirmRetiroLayout.setHorizontalGroup(
            btnConfirmRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnConfirmRetiroLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(35, 35, 35))
        );
        btnConfirmRetiroLayout.setVerticalGroup(
            btnConfirmRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlOne.add(btnConfirmRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, 190, 40));

        pnlRetreat.setBackground(new Color(255, 255, 255, 123));
        pnlRetreat.setRoundBottomLeft(30);
        pnlRetreat.setRoundBottomRight(30);
        pnlRetreat.setRoundTopLeft(30);
        pnlRetreat.setRoundTopRight(30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese el monto a Retirar");

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(320, 54));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMoney.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtMoney.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMoney.setText("0.00");
        txtMoney.setBorder(null);
        panelRound2.add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 292, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("$");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        javax.swing.GroupLayout pnlRetreatLayout = new javax.swing.GroupLayout(pnlRetreat);
        pnlRetreat.setLayout(pnlRetreatLayout);
        pnlRetreatLayout.setHorizontalGroup(
            pnlRetreatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetreatLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlRetreatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlRetreatLayout.setVerticalGroup(
            pnlRetreatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRetreatLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pnlOne.add(pnlRetreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 410, 170));

        lbFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/wallpaper.png"))); // NOI18N
        pnlOne.add(lbFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmRetiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmRetiroMouseEntered
        // TODO add your handling code here:
        btnConfirmRetiro.setBackground(new Color(60,67,127));
        btnConfirmRetiro.repaint();

    }//GEN-LAST:event_btnConfirmRetiroMouseEntered

    private void btnConfirmRetiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmRetiroMouseExited
        // TODO add your handling code here:
        btnConfirmRetiro.setBackground(new Color(51,0,102));
        btnConfirmRetiro.repaint();
    }//GEN-LAST:event_btnConfirmRetiroMouseExited

    private void btnConfirmRetiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmRetiroMouseClicked
        double money = Double.parseDouble(txtMoney.getText());
        if(txtMoney.getText().isEmpty() || money == 0.0){
            JOptionPane.showMessageDialog(null, "No puedes hacer un retiro de $0.0 dolares");
            return;           
        }
        setRetrat();
    }//GEN-LAST:event_btnConfirmRetiroMouseClicked

    private void lbReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbReturnMouseClicked
        windows.showPanel(new MPanelOptions(windows, account));
    }//GEN-LAST:event_lbReturnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.PanelRound btnConfirmRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbFound;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbReturn;
    private javax.swing.JLabel lbTitle;
    private ComponentRoundJilmar.PanelRound panelRound2;
    private javax.swing.JPanel pnlOne;
    private ComponentRoundJilmar.PanelRound pnlRetreat;
    private ComponentRoundJilmar.PanelRound pnlTitle;
    private javax.swing.JTextField txtMoney;
    // End of variables declaration//GEN-END:variables

    private void setRetrat() {
        double money = Double.parseDouble(txtMoney.getText());
        double balance = account.getBalance();
        if(money < 5 || money > 500) {
            JOptionPane.showMessageDialog(null, "El monto a retirar no es permitido","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(money > balance) {
            JOptionPane.showMessageDialog(null, "Tu cuenta no tiene el saldo suficiente","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        account.setBalance(money);
        aplication.applicationn(account);
        
        windows.setDates();
        windows.showPanel(new MPanelOptions(windows,account));
    }
        
}
