
package p3tarea3grupo3.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import p3tarea3grupo3.controller.Account;
import p3tarea3grupo3.controller.ListClient;
import p3tarea3grupo3.controller.designpattern.factorymethod.Transaction;
import p3tarea3grupo3.controller.designpattern.factorymethod.Transfer;
import p3tarea3grupo3.controller.designpattern.factorymethod.Withdrawal;

public class MPanelTransfer extends javax.swing.JPanel {

    Transaction aplication;
    Transaction subtract;
   
    MainWindows windows;
    Account account;
    Account searchAccount;
    ListClient client;
    
    public MPanelTransfer() {
        initComponents();
    }
    
    public MPanelTransfer(MainWindows windows, Account account) {
        initComponents();
        this.windows = windows;
        this.account = account;
        aplication = new Transfer();
        subtract = new Withdrawal();
        //Singleton
        client = ListClient.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOne = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panelRound1 = new ComponentRoundJilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelRound2 = new ComponentRoundJilmar.PanelRound();
        txtDiner = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        panelRound3 = new ComponentRoundJilmar.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        txtNumberCount = new javax.swing.JTextField();
        panelRound4 = new ComponentRoundJilmar.PanelRound();
        jTextField3 = new javax.swing.JTextField();
        panelRound5 = new ComponentRoundJilmar.PanelRound();
        lblNumberAccount = new javax.swing.JLabel();
        lblDestinationn = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnConfirmTransfer = new ComponentRoundJilmar.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFound = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlOne.setBackground(new java.awt.Color(255, 255, 255));
        pnlOne.setOpaque(false);
        pnlOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese el monto a transferir");
        pnlOne.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese un comentario");
        pnlOne.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, -1, -1));

        panelRound1.setBackground(new Color(255, 255, 255, 123));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transferencias");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/nextOne.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/return.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(16, 16, 16))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlOne.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, 60));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(320, 54));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtDiner.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txtDiner.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiner.setText("0.00");
        txtDiner.setBorder(null);
        txtDiner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDinerActionPerformed(evt);
            }
        });
        panelRound2.add(txtDiner, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, 270, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("$");
        panelRound2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 30, 30));

        pnlOne.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 380, 40));

        panelRound3.setBackground(new java.awt.Color(255, 255, 255));
        panelRound3.setPreferredSize(new java.awt.Dimension(320, 54));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/search.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelRound3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 38, 40));

        txtNumberCount.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txtNumberCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNumberCount.setBorder(null);
        txtNumberCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberCountActionPerformed(evt);
            }
        });
        panelRound3.add(txtNumberCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 0, 270, 40));

        pnlOne.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 380, 40));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setPreferredSize(new java.awt.Dimension(320, 54));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBorder(null);
        panelRound4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, 300, 40));

        pnlOne.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 380, 40));

        panelRound5.setBackground(new Color(255, 255, 255, 123));
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumberAccount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberAccount.setForeground(new java.awt.Color(255, 255, 255));
        lblNumberAccount.setText("2200440110 ");
        panelRound5.add(lblNumberAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 71, -1, -1));

        lblDestinationn.setBackground(new java.awt.Color(51, 0, 153));
        lblDestinationn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDestinationn.setForeground(new java.awt.Color(51, 0, 153));
        lblDestinationn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDestinationn.setText("Usuario");
        panelRound5.add(lblDestinationn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 35, 350, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Para");
        panelRound5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nro. ");
        panelRound5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, -1, -1));

        pnlOne.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 380, 110));

        btnConfirmTransfer.setBackground(new java.awt.Color(51, 0, 102));
        btnConfirmTransfer.setPreferredSize(new java.awt.Dimension(100, 54));
        btnConfirmTransfer.setRoundBottomLeft(30);
        btnConfirmTransfer.setRoundBottomRight(30);
        btnConfirmTransfer.setRoundTopLeft(30);
        btnConfirmTransfer.setRoundTopRight(30);
        btnConfirmTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConfirmTransferMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConfirmTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConfirmTransferMouseExited(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confirmar Trasferencia");

        javax.swing.GroupLayout btnConfirmTransferLayout = new javax.swing.GroupLayout(btnConfirmTransfer);
        btnConfirmTransfer.setLayout(btnConfirmTransferLayout);
        btnConfirmTransferLayout.setHorizontalGroup(
            btnConfirmTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConfirmTransferLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        btnConfirmTransferLayout.setVerticalGroup(
            btnConfirmTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlOne.add(btnConfirmTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, 190, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Busque el Beneficiario");
        pnlOne.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        lbFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/wallpaper.png"))); // NOI18N
        pnlOne.add(lbFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(pnlOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmTransferMouseEntered
        // TODO add your handling code here:
       btnConfirmTransfer.setBackground(new Color(105,0,64));
       btnConfirmTransfer.repaint();
        
    }//GEN-LAST:event_btnConfirmTransferMouseEntered

    private void btnConfirmTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmTransferMouseExited
        // TODO add your handling code here:
       btnConfirmTransfer.setBackground(new Color(51,0,102));
       btnConfirmTransfer.repaint();
    }//GEN-LAST:event_btnConfirmTransferMouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        windows.showPanel(new MPanelOptions(windows, account));
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtDinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDinerActionPerformed

    private void txtNumberCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberCountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberCountActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        serchClient();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnConfirmTransferMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConfirmTransferMouseClicked
        tranfer();
    }//GEN-LAST:event_btnConfirmTransferMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.PanelRound btnConfirmTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbFound;
    private javax.swing.JLabel lblDestinationn;
    private javax.swing.JLabel lblNumberAccount;
    private ComponentRoundJilmar.PanelRound panelRound1;
    private ComponentRoundJilmar.PanelRound panelRound2;
    private ComponentRoundJilmar.PanelRound panelRound3;
    private ComponentRoundJilmar.PanelRound panelRound4;
    private ComponentRoundJilmar.PanelRound panelRound5;
    private javax.swing.JPanel pnlOne;
    private javax.swing.JTextField txtDiner;
    private javax.swing.JTextField txtNumberCount;
    // End of variables declaration//GEN-END:variables

    private void serchClient() {       
        String numberClient = txtNumberCount.getText();
        List<Account> account = client.getAccount();
        boolean value = false;
        for (Account a : account) {         
            if(a.getAccountNumber().equals(numberClient)) {
                searchAccount = a;
                lblDestinationn.setText(searchAccount.getTitular());
                lblNumberAccount.setText(searchAccount.getAccountNumber());
                value = true;
                break;
            }
        }
        
        if(!value) {
            JOptionPane.showMessageDialog(this, "No se encontró ningún usuario con el número de cuenta proporcionado.", "Usuario no encontrado", JOptionPane.ERROR_MESSAGE);
            lblDestinationn.setText("Usuario no Existe");
            lblNumberAccount.setText("----------");
        }
       
    }
    
    public void tranfer() {
        String numberCount = txtNumberCount.getText();
        String nameDestination = lblDestinationn.getText();
        Double balance = account.getBalance();
        Double newBalance = Double.parseDouble(txtDiner.getText());
    
        if(txtNumberCount.getText().isEmpty() || nameDestination.equals("Usuario no Existe") || nameDestination.equals("Usuario no Existe")){
            JOptionPane.showMessageDialog(null, "El numero de cuenta no puede estar vacio", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Double total = balance - newBalance;
        
        //Valor a transferir
        searchAccount.setBalance(newBalance);       
        aplication.applicationn(searchAccount);
        
        //Valor a restar de la cuenta actual
        account.setBalance(total);
        subtract.applicationn(account);
        
        windows.setDates();
        windows.showPanel(new MPanelOptions(windows,account));
        
    }

    
       
    
}
