
package p3tarea3grupo3.view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class RegisterWindows extends javax.swing.JFrame {
    
    ValidateData validate;
    ValidateDataComboBox validateCombo;
    KeyboardEvents event;
    private int initX, initY;
    
    public RegisterWindows() {
        initComponents();
        validate = new ValidateData();
        validateCombo = new ValidateDataComboBox();
        event = new KeyboardEvents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelActions = new javax.swing.JPanel();
        btnMinimeze = new javax.swing.JLabel();
        btnExit = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelRegister = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCodeFinger = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        CalendarDateOfBirth = new com.toedter.calendar.JDateChooser();
        txtPhone = new javax.swing.JTextField();
        cmbStatus = new javax.swing.JComboBox<>();
        txtHomeAddres = new javax.swing.JTextField();
        cmbOccupation = new javax.swing.JComboBox<>();
        txtMail = new javax.swing.JTextField();
        txtNationality = new javax.swing.JTextField();
        cmbProvince = new javax.swing.JComboBox<>();
        cmbCity = new javax.swing.JComboBox<>();
        txtReferenceName = new javax.swing.JTextField();
        txtReferencePhone = new javax.swing.JTextField();
        cmbAccount = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btnClear = new ComponentRoundJilmar.PanelRound();
        jLabel17 = new javax.swing.JLabel();
        btnRegister = new ComponentRoundJilmar.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        btnGoBack = new ComponentRoundJilmar.PanelRound();
        jLabel19 = new javax.swing.JLabel();
        PanelWallpaper = new javax.swing.JPanel();
        panelRound2 = new ComponentRoundJilmar.PanelRound();
        panelRound9 = new ComponentRoundJilmar.PanelRound();
        panelRound13 = new ComponentRoundJilmar.PanelRound();
        panelRound14 = new ComponentRoundJilmar.PanelRound();
        panelRound6 = new ComponentRoundJilmar.PanelRound();
        panelRound15 = new ComponentRoundJilmar.PanelRound();
        panelRound16 = new ComponentRoundJilmar.PanelRound();
        panelRound19 = new ComponentRoundJilmar.PanelRound();
        panelRound18 = new ComponentRoundJilmar.PanelRound();
        panelRound17 = new ComponentRoundJilmar.PanelRound();
        lbFound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelActions.setBackground(new java.awt.Color(0, 0, 0));
        PanelActions.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                PanelActionsMouseDragged(evt);
            }
        });
        PanelActions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelActionsMouseEntered(evt);
            }
        });
        PanelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMinimeze.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimeze.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMinimeze.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimeze.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimeze.setText("-");
        btnMinimeze.setOpaque(true);
        btnMinimeze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimezeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimezeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMinimezeMouseExited(evt);
            }
        });
        PanelActions.add(btnMinimeze, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 30));

        btnExit.setBackground(new java.awt.Color(0, 0, 0));
        btnExit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setText("X");
        btnExit.setOpaque(true);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        PanelActions.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 30));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/Icon.png"))); // NOI18N
        lblIcon.setText("jLabel2");
        PanelActions.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MayLiJi");
        PanelActions.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 60, 30));

        getContentPane().add(PanelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelRegister.setBackground(new java.awt.Color(255, 255, 255));
        PanelRegister.setOpaque(false);
        PanelRegister.setPreferredSize(new java.awt.Dimension(1220, 670));
        PanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 51, 51));
        lbTitle.setText("Datos como cliente");
        PanelRegister.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        lbName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(51, 51, 51));
        lbName.setText("Nombres ");
        PanelRegister.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Apellidos");
        PanelRegister.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cédula de Identidad");
        PanelRegister.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Codigo Dactilar");
        PanelRegister.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Fecha de Nacimiento");
        PanelRegister.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Correo Electrónico");
        PanelRegister.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Estado Civil");
        PanelRegister.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Teléfono");
        PanelRegister.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Dirección");
        PanelRegister.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Ocupación");
        PanelRegister.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nacionalidad");
        PanelRegister.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Provincia");
        PanelRegister.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Ciudad");
        PanelRegister.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Tipo de Cuenta");
        PanelRegister.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, -1, -1));

        txtCodeFinger.setBorder(null);
        txtCodeFinger.setPreferredSize(new java.awt.Dimension(330, 30));
        txtCodeFinger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodeFingerKeyTyped(evt);
            }
        });
        PanelRegister.add(txtCodeFinger, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        txtName.setBorder(null);
        txtName.setPreferredSize(new java.awt.Dimension(330, 30));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNameKeyTyped(evt);
            }
        });
        PanelRegister.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        txtID.setBorder(null);
        txtID.setPreferredSize(new java.awt.Dimension(330, 30));
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });
        PanelRegister.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtLastName.setBorder(null);
        txtLastName.setPreferredSize(new java.awt.Dimension(330, 30));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });
        PanelRegister.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        CalendarDateOfBirth.setBackground(new java.awt.Color(255, 255, 255));
        CalendarDateOfBirth.setForeground(new java.awt.Color(51, 51, 51));
        CalendarDateOfBirth.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelRegister.add(CalendarDateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 350, -1));

        txtPhone.setBorder(null);
        txtPhone.setPreferredSize(new java.awt.Dimension(330, 30));
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPhoneKeyTyped(evt);
            }
        });
        PanelRegister.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));
        cmbStatus.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelRegister.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        txtHomeAddres.setBorder(null);
        txtHomeAddres.setPreferredSize(new java.awt.Dimension(330, 30));
        txtHomeAddres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHomeAddresKeyTyped(evt);
            }
        });
        PanelRegister.add(txtHomeAddres, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, -1, -1));

        cmbOccupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Estudiante", "Maestro(a) / Profesor(a)", "Médico(a)", "Ingeniero(a)", "Abogado(a)", "Arquitecto(a)", "Contador(a)", "Empresario(a)", "Artista", "Músico(a)", "Actor / Actriz", "Escritor(a)", "Fotógrafo(a)", "Diseñador(a) gráfico(a)", "Programador(a)", "Chef / Cocinero(a)", "Agricultor(a)", "Artesano(a)", "Jardinero(a)", "Peluquero(a) / Estilista", "Bombero(a)", "Policía", "Paramédico(a)", "Enfermero(a)", "Psicólogo(a)", "Terapeuta", "Consultor(a)", "Investigador(a)", "Veterinario(a)", "Voluntario(a)" }));
        cmbOccupation.setBorder(null);
        cmbOccupation.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelRegister.add(cmbOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, -1, -1));

        txtMail.setBorder(null);
        txtMail.setPreferredSize(new java.awt.Dimension(330, 30));
        PanelRegister.add(txtMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, -1, -1));

        txtNationality.setBorder(null);
        txtNationality.setPreferredSize(new java.awt.Dimension(330, 30));
        txtNationality.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNationalityKeyTyped(evt);
            }
        });
        PanelRegister.add(txtNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 200, -1, -1));

        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", " " }));
        cmbProvince.setBorder(null);
        cmbProvince.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelRegister.add(cmbProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 290, 160, 30));

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "" }));
        cmbCity.setBorder(null);
        cmbCity.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelRegister.add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 160, 30));

        txtReferenceName.setBorder(null);
        txtReferenceName.setPreferredSize(new java.awt.Dimension(330, 30));
        txtReferenceName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReferenceNameKeyTyped(evt);
            }
        });
        PanelRegister.add(txtReferenceName, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 470, -1, -1));

        txtReferencePhone.setBorder(null);
        txtReferencePhone.setPreferredSize(new java.awt.Dimension(330, 30));
        txtReferencePhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtReferencePhoneKeyTyped(evt);
            }
        });
        PanelRegister.add(txtReferencePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, -1, -1));

        cmbAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Cuenta de Ahorros", "Cuenta Corriente" }));
        cmbAccount.setBorder(null);
        cmbAccount.setPreferredSize(new java.awt.Dimension(350, 30));
        cmbAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountActionPerformed(evt);
            }
        });
        PanelRegister.add(cmbAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 380, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Nombre de Referencia");
        PanelRegister.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Teléfono de Referencia");
        PanelRegister.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, -1, -1));

        btnClear.setBackground(new java.awt.Color(131, 65, 255));
        btnClear.setRoundBottomLeft(20);
        btnClear.setRoundBottomRight(20);
        btnClear.setRoundTopLeft(20);
        btnClear.setRoundTopRight(20);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Limpiar");

        javax.swing.GroupLayout btnClearLayout = new javax.swing.GroupLayout(btnClear);
        btnClear.setLayout(btnClearLayout);
        btnClearLayout.setHorizontalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClearLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(33, 33, 33))
        );
        btnClearLayout.setVerticalGroup(
            btnClearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnClearLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        PanelRegister.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 610, 120, 30));

        btnRegister.setBackground(new java.awt.Color(131, 65, 255));
        btnRegister.setPreferredSize(new java.awt.Dimension(120, 30));
        btnRegister.setRoundBottomLeft(20);
        btnRegister.setRoundBottomRight(20);
        btnRegister.setRoundTopLeft(20);
        btnRegister.setRoundTopRight(20);
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Registrarse");

        javax.swing.GroupLayout btnRegisterLayout = new javax.swing.GroupLayout(btnRegister);
        btnRegister.setLayout(btnRegisterLayout);
        btnRegisterLayout.setHorizontalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnRegisterLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(19, 19, 19))
        );
        btnRegisterLayout.setVerticalGroup(
            btnRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnRegisterLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        PanelRegister.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 610, -1, 30));

        btnGoBack.setBackground(new java.awt.Color(131, 65, 255));
        btnGoBack.setPreferredSize(new java.awt.Dimension(120, 30));
        btnGoBack.setRoundBottomLeft(20);
        btnGoBack.setRoundBottomRight(20);
        btnGoBack.setRoundTopLeft(20);
        btnGoBack.setRoundTopRight(20);
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGoBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGoBackMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Regresar");

        javax.swing.GroupLayout btnGoBackLayout = new javax.swing.GroupLayout(btnGoBack);
        btnGoBack.setLayout(btnGoBackLayout);
        btnGoBackLayout.setHorizontalGroup(
            btnGoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGoBackLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(27, 27, 27))
        );
        btnGoBackLayout.setVerticalGroup(
            btnGoBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGoBackLayout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        PanelRegister.add(btnGoBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 610, -1, 30));

        getContentPane().add(PanelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 670));

        PanelWallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 350, 30));

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound9.setRoundBottomLeft(20);
        panelRound9.setRoundBottomRight(20);
        panelRound9.setRoundTopLeft(20);
        panelRound9.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound9Layout = new javax.swing.GroupLayout(panelRound9);
        panelRound9.setLayout(panelRound9Layout);
        panelRound9Layout.setHorizontalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound9Layout.setVerticalGroup(
            panelRound9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        panelRound13.setBackground(new java.awt.Color(255, 255, 255));
        panelRound13.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound13.setRoundBottomLeft(20);
        panelRound13.setRoundBottomRight(20);
        panelRound13.setRoundTopLeft(20);
        panelRound13.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound13Layout = new javax.swing.GroupLayout(panelRound13);
        panelRound13.setLayout(panelRound13Layout);
        panelRound13Layout.setHorizontalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound13Layout.setVerticalGroup(
            panelRound13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        panelRound14.setBackground(new java.awt.Color(255, 255, 255));
        panelRound14.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound14.setRoundBottomLeft(20);
        panelRound14.setRoundBottomRight(20);
        panelRound14.setRoundTopLeft(20);
        panelRound14.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound14Layout = new javax.swing.GroupLayout(panelRound14);
        panelRound14.setLayout(panelRound14Layout);
        panelRound14Layout.setHorizontalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound14Layout.setVerticalGroup(
            panelRound14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound6.setRoundBottomLeft(20);
        panelRound6.setRoundBottomRight(20);
        panelRound6.setRoundTopLeft(20);
        panelRound6.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound6Layout = new javax.swing.GroupLayout(panelRound6);
        panelRound6.setLayout(panelRound6Layout);
        panelRound6Layout.setHorizontalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound6Layout.setVerticalGroup(
            panelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound15.setRoundBottomLeft(20);
        panelRound15.setRoundBottomRight(20);
        panelRound15.setRoundTopLeft(20);
        panelRound15.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        panelRound16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound16.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound16.setRoundBottomLeft(20);
        panelRound16.setRoundBottomRight(20);
        panelRound16.setRoundTopLeft(20);
        panelRound16.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        panelRound19.setBackground(new java.awt.Color(255, 255, 255));
        panelRound19.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound19.setRoundBottomLeft(20);
        panelRound19.setRoundBottomRight(20);
        panelRound19.setRoundTopLeft(20);
        panelRound19.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound19Layout = new javax.swing.GroupLayout(panelRound19);
        panelRound19.setLayout(panelRound19Layout);
        panelRound19Layout.setHorizontalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound19Layout.setVerticalGroup(
            panelRound19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound19, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));

        panelRound18.setBackground(new java.awt.Color(255, 255, 255));
        panelRound18.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound18.setRoundBottomLeft(20);
        panelRound18.setRoundBottomRight(20);
        panelRound18.setRoundTopLeft(20);
        panelRound18.setRoundTopRight(20);

        javax.swing.GroupLayout panelRound18Layout = new javax.swing.GroupLayout(panelRound18);
        panelRound18.setLayout(panelRound18Layout);
        panelRound18Layout.setHorizontalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound18Layout.setVerticalGroup(
            panelRound18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound18, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, -1, -1));

        panelRound17.setBackground(new java.awt.Color(255, 255, 255));
        panelRound17.setPreferredSize(new java.awt.Dimension(350, 30));
        panelRound17.setRoundBottomLeft(20);
        panelRound17.setRoundBottomRight(20);
        panelRound17.setRoundTopLeft(20);
        panelRound17.setRoundTopRight(30);

        javax.swing.GroupLayout panelRound17Layout = new javax.swing.GroupLayout(panelRound17);
        panelRound17.setLayout(panelRound17Layout);
        panelRound17Layout.setHorizontalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelRound17Layout.setVerticalGroup(
            panelRound17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        PanelWallpaper.add(panelRound17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 560, -1, -1));

        lbFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/registerFocus.png"))); // NOI18N
        PanelWallpaper.add(lbFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(Color.red);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(Color.black);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMinimezeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimezeMouseClicked
         this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimezeMouseClicked

    private void btnMinimezeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimezeMouseEntered
        btnMinimeze.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_btnMinimezeMouseEntered

    private void btnMinimezeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimezeMouseExited
        btnMinimeze.setBackground(Color.black);
    }//GEN-LAST:event_btnMinimezeMouseExited

    private void PanelActionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelActionsMouseEntered
        initX = evt.getX();
        initY = evt.getY();
    }//GEN-LAST:event_PanelActionsMouseEntered

    private void PanelActionsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelActionsMouseDragged
        int newX  = getLocation().x + evt.getX() - initX;
        int newY = getLocation().y + evt.getY() - initY;

        this.setLocation(newX, newY);
    }//GEN-LAST:event_PanelActionsMouseDragged

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void cmbAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccountActionPerformed

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        btnClear.setBackground(new Color(65,78,125));
        btnClear.repaint();
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here
        btnClear.setBackground(new Color(131,65,255));
        btnClear.repaint();
    }//GEN-LAST:event_btnClearMouseExited

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(65,78,125));
        btnRegister.repaint();
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
        btnRegister.setBackground(new Color(131,65,255));
        btnRegister.repaint();
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnGoBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseEntered
        // TODO add your handling code here:
        btnGoBack.setBackground(new Color(65,78,125));
        btnGoBack.repaint();
    }//GEN-LAST:event_btnGoBackMouseEntered

    private void btnGoBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseExited
        // TODO add your handling code here:
        btnGoBack.setBackground(new Color(131,65,255));
        btnGoBack.repaint();
    }//GEN-LAST:event_btnGoBackMouseExited

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        if(!validate.validateField(PanelRegister) || !validateCombo.validateField(PanelRegister)) {
            JOptionPane.showMessageDialog(this, "Existen Campos Vacios","CAUTION",JOptionPane.INFORMATION_MESSAGE);
        }else {
            saveInformation();
        }
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void txtNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyTyped
        event.textSpaceKeyPress(evt);
    }//GEN-LAST:event_txtNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        event.textSpaceKeyPress(evt);
    }//GEN-LAST:event_txtLastNameKeyTyped

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        event.dateNum(txtID.getText(), evt);
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtCodeFingerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodeFingerKeyTyped
        event.textAndNumber(evt);
    }//GEN-LAST:event_txtCodeFingerKeyTyped

    private void txtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyTyped
        event.dateNum(txtPhone.getText(), evt);
    }//GEN-LAST:event_txtPhoneKeyTyped

    private void txtHomeAddresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHomeAddresKeyTyped
        event.textAndNumber(evt);
    }//GEN-LAST:event_txtHomeAddresKeyTyped

    private void txtNationalityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNationalityKeyTyped
        event.textKeyPress(evt);
    }//GEN-LAST:event_txtNationalityKeyTyped

    private void txtReferenceNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferenceNameKeyTyped
        event.textSpaceKeyPress(evt);
    }//GEN-LAST:event_txtReferenceNameKeyTyped

    private void txtReferencePhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReferencePhoneKeyTyped
        event.dateNum(txtReferencePhone.getText(), evt); 
    }//GEN-LAST:event_txtReferencePhoneKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterWindows().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser CalendarDateOfBirth;
    private javax.swing.JPanel PanelActions;
    private javax.swing.JPanel PanelRegister;
    private javax.swing.JPanel PanelWallpaper;
    private ComponentRoundJilmar.PanelRound btnClear;
    private javax.swing.JLabel btnExit;
    private ComponentRoundJilmar.PanelRound btnGoBack;
    private javax.swing.JLabel btnMinimeze;
    private ComponentRoundJilmar.PanelRound btnRegister;
    private javax.swing.JComboBox<String> cmbAccount;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbOccupation;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbFound;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lblIcon;
    private ComponentRoundJilmar.PanelRound panelRound13;
    private ComponentRoundJilmar.PanelRound panelRound14;
    private ComponentRoundJilmar.PanelRound panelRound15;
    private ComponentRoundJilmar.PanelRound panelRound16;
    private ComponentRoundJilmar.PanelRound panelRound17;
    private ComponentRoundJilmar.PanelRound panelRound18;
    private ComponentRoundJilmar.PanelRound panelRound19;
    private ComponentRoundJilmar.PanelRound panelRound2;
    private ComponentRoundJilmar.PanelRound panelRound6;
    private ComponentRoundJilmar.PanelRound panelRound9;
    private javax.swing.JTextField txtCodeFinger;
    private javax.swing.JTextField txtHomeAddres;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNationality;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtReferenceName;
    private javax.swing.JTextField txtReferencePhone;
    // End of variables declaration//GEN-END:variables

    public void saveInformation() {
       
        String name = txtName.getText();
        String lastName = txtLastName.getText();
        String identification = txtID.getText();
        String code = txtCodeFinger.getText();
        String birthDate = CalendarDateOfBirth.getToolTipText();
        String status = (String) cmbStatus.getSelectedItem();
        long phone = Long.parseLong(txtPhone.getText());
        String occupation = (String) cmbOccupation.getSelectedItem();
        String email = txtMail.getText();
        String nationality = txtNationality.getText();
        String province = (String) cmbProvince.getSelectedItem();
        String city = (String) cmbCity.getSelectedItem();
        String referenceName = txtReferenceName.getText();
        long referencePhone = Long.parseLong(txtReferencePhone.getText());
        
    }
    
}
