
package p3tarea3grupo3.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.bson.Document;
import p3tarea3grupo3.controller.Account;
import p3tarea3grupo3.controller.Client;
import p3tarea3grupo3.controller.ListClient;
import p3tarea3grupo3.model.CreateMongo;

public class RPanelAccount extends javax.swing.JPanel {
    
    private ListClient listClient;
    private List<Account> accountList;
    private Account account;
    private Client client;
    private CreateMongo createMongo;
    String accountNumber;
    String user;
    
    public RPanelAccount(Client client) {
        initComponents();
        
        System.out.println("Entro en el rgeistro final " + client.getName());
        //Singleton
        listClient = ListClient.getInstance();
        accountList = listClient.getAccount();
        this.client = client;
        account = new Account();
        createMongo = new CreateMongo();
        
        accountNumber = String.valueOf(1000000000 + (accountList.size() + 1));
        lblNumberCta.setText(accountNumber);
        user = createUser();
        lblUser.setText(user);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOne = new javax.swing.JPanel();
        pnlTitle = new ComponentRoundJilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        pnlInformation = new ComponentRoundJilmar.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelRound2 = new ComponentRoundJilmar.PanelRound();
        txtPin = new javax.swing.JTextField();
        panelRound4 = new ComponentRoundJilmar.PanelRound();
        txtPasword = new javax.swing.JTextField();
        lblNumberCta = new ComponentRoundJilmar.LabelRound();
        lblUser = new ComponentRoundJilmar.LabelRound();
        panelRound1 = new ComponentRoundJilmar.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEnter = new ComponentRoundJilmar.LabelRound();
        lbFound = new javax.swing.JLabel();

        pnlOne.setBackground(new java.awt.Color(255, 255, 255));
        pnlOne.setPreferredSize(new java.awt.Dimension(660, 670));
        pnlOne.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setBackground(new Color(255, 255, 255, 123));
        pnlTitle.setRoundBottomLeft(30);
        pnlTitle.setRoundBottomRight(30);
        pnlTitle.setRoundTopLeft(30);
        pnlTitle.setRoundTopRight(30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos de Cuenta");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/nextOne.png"))); // NOI18N

        lblReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/return.png"))); // NOI18N

        javax.swing.GroupLayout pnlTitleLayout = new javax.swing.GroupLayout(pnlTitle);
        pnlTitle.setLayout(pnlTitleLayout);
        pnlTitleLayout.setHorizontalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addComponent(lblReturn)
                .addGap(16, 16, 16))
        );
        pnlTitleLayout.setVerticalGroup(
            pnlTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblReturn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlTitleLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlOne.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 620, 60));

        pnlInformation.setBackground(new Color(255, 255, 255, 123));
        pnlInformation.setRoundBottomLeft(30);
        pnlInformation.setRoundBottomRight(30);
        pnlInformation.setRoundTopLeft(30);
        pnlInformation.setRoundTopRight(30);
        pnlInformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(51, 0, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 153));
        jLabel7.setText("CAMILA MAYTE PERRAZO GUERRA");
        pnlInformation.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 21, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Numero de Cuenta");
        pnlInformation.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 130, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contraseña");
        pnlInformation.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 305, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Saldo Inicial");
        pnlInformation.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PIN");
        pnlInformation.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 245, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuario");
        pnlInformation.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 190, -1, -1));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setPreferredSize(new java.awt.Dimension(48, 25));
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);

        txtPin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPin.setForeground(new java.awt.Color(51, 0, 102));
        txtPin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPin.setBorder(null);
        txtPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPin)
        );

        pnlInformation.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 245, 175, -1));

        panelRound4.setBackground(new java.awt.Color(255, 255, 255));
        panelRound4.setPreferredSize(new java.awt.Dimension(48, 25));
        panelRound4.setRoundBottomLeft(30);
        panelRound4.setRoundBottomRight(30);
        panelRound4.setRoundTopLeft(30);
        panelRound4.setRoundTopRight(30);

        txtPasword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPasword.setForeground(new java.awt.Color(51, 0, 102));
        txtPasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPasword.setBorder(null);
        txtPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPasword)
        );

        pnlInformation.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 305, 175, -1));

        lblNumberCta.setBackground(new java.awt.Color(255, 255, 255));
        lblNumberCta.setForeground(new java.awt.Color(51, 0, 102));
        lblNumberCta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumberCta.setText("2206122194");
        lblNumberCta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNumberCta.setRoundBottomLeft(30);
        lblNumberCta.setRoundBottomRight(30);
        lblNumberCta.setRoundTopLeft(30);
        lblNumberCta.setRoundTopRight(30);
        pnlInformation.add(lblNumberCta, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 133, 175, -1));

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setForeground(new java.awt.Color(51, 0, 102));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("camilu");
        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUser.setMaximumSize(new java.awt.Dimension(96, 20));
        lblUser.setMinimumSize(new java.awt.Dimension(96, 20));
        lblUser.setPreferredSize(new java.awt.Dimension(96, 20));
        lblUser.setRoundBottomLeft(30);
        lblUser.setRoundBottomRight(30);
        lblUser.setRoundTopLeft(30);
        lblUser.setRoundTopRight(30);
        pnlInformation.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 190, 175, 25));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("$");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 102));
        jLabel8.setText("0.00");
        panelRound1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 40, 25));

        pnlInformation.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 25));

        pnlOne.add(pnlInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 420, 360));

        btnEnter.setBackground(new java.awt.Color(0, 0, 0));
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEnter.setText("Registrar");
        btnEnter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnEnter.setRoundBottomLeft(40);
        btnEnter.setRoundBottomRight(40);
        btnEnter.setRoundTopLeft(40);
        btnEnter.setRoundTopRight(40);
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterMouseExited(evt);
            }
        });
        pnlOne.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 130, 40));

        lbFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/wallpaper.png"))); // NOI18N
        pnlOne.add(lbFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlOne, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlOne, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaswordActionPerformed

    private void txtPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinActionPerformed

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        if(txtPin.getText().isEmpty() || txtPasword.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Existen Campos Vacios","CAUTION",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        registerMongo();
        
        LoginWindows login = new LoginWindows();
        login.setVisible(true);
        
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RPanelAccount.this);
        frame.dispose();
        
        
    }//GEN-LAST:event_btnEnterMouseClicked

    private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseEntered
        btnEnter.setBackground(Color.white);
        btnEnter.setForeground(Color.black);
    }//GEN-LAST:event_btnEnterMouseEntered

    private void btnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseExited
        btnEnter.setBackground(Color.black);
        btnEnter.setForeground(Color.white);
    }//GEN-LAST:event_btnEnterMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ComponentRoundJilmar.LabelRound btnEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbFound;
    private ComponentRoundJilmar.LabelRound lblNumberCta;
    private javax.swing.JLabel lblReturn;
    private ComponentRoundJilmar.LabelRound lblUser;
    private ComponentRoundJilmar.PanelRound panelRound1;
    private ComponentRoundJilmar.PanelRound panelRound2;
    private ComponentRoundJilmar.PanelRound panelRound4;
    private ComponentRoundJilmar.PanelRound pnlInformation;
    private javax.swing.JPanel pnlOne;
    private ComponentRoundJilmar.PanelRound pnlTitle;
    private javax.swing.JTextField txtPasword;
    private javax.swing.JTextField txtPin;
    // End of variables declaration//GEN-END:variables

    private void registerMongo() {
        int id = accountList.size() + 1;
        String accountNumber = lblNumberCta.getText();
        String titular = client.getName() + " " + client.getLastName();
        String user = lblUser.getText();
        String password = txtPasword.getText();
        String pin = txtPin.getText();
        double balance = 1.0;
        
        Account ac = new Account(id, accountNumber, titular, user, password, pin, balance, client);
        Document doc = account.getDocument(ac);
        createMongo.addDocument(doc);
        
        
    }
    
    public String createUser(){
        String[] user = client.getName().split(" ");
        String nam = user[0].substring(0,1).toLowerCase() + user[1].substring(0,1).toLowerCase();
        String[]last = client.getLastName().split(" ");
        String lastn = last[0].toLowerCase();
        String userName = (nam+lastn);
        return userName;
    }
}
