/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p3tarea3grupo3.view;

import java.awt.Color;
import java.util.List;
import javax.swing.JComboBox;
import org.bson.Document;
import p3tarea3grupo3.controller.Account;
import p3tarea3grupo3.controller.ListClient;
import p3tarea3grupo3.controller.SearchData;
import p3tarea3grupo3.model.DeleteMongo;
import p3tarea3grupo3.model.UpdateMongo;


/**
 *
 * @author HOME
 */
public class UpdataData extends javax.swing.JFrame {
DeleteMongo deleteMongo;

    /**
     * Creates new form UpdataData
     */
    public UpdataData() {
        initComponents();
        deleteMongo = new DeleteMongo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelActions = new javax.swing.JPanel();
        PanelWallpaper = new javax.swing.JPanel();
        btnDelete = new ComponentRoundJilmar.PanelRound();
        lblDelete = new javax.swing.JLabel();
        pnlBirthDate = new ComponentRoundJilmar.PanelRound();
        txtBirthDate = new javax.swing.JTextField();
        pnlSearch = new ComponentRoundJilmar.PanelRound();
        btnSetData = new ComponentRoundJilmar.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        btnSearch = new ComponentRoundJilmar.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnUpdata = new ComponentRoundJilmar.PanelRound();
        jLabel42 = new javax.swing.JLabel();
        pnlBalance = new ComponentRoundJilmar.PanelRound();
        txtBalance = new javax.swing.JTextField();
        lblTitleBalance = new javax.swing.JLabel();
        pnlPin = new ComponentRoundJilmar.PanelRound();
        txtPIN = new javax.swing.JTextField();
        lblTitlePin = new javax.swing.JLabel();
        pnlPassword = new ComponentRoundJilmar.PanelRound();
        txtPassword = new javax.swing.JTextField();
        lblTitlePassword = new javax.swing.JLabel();
        pnlUser = new ComponentRoundJilmar.PanelRound();
        txtUser = new javax.swing.JTextField();
        lblTitleUser = new javax.swing.JLabel();
        pnlTitular = new ComponentRoundJilmar.PanelRound();
        txtTitular = new javax.swing.JTextField();
        lblTitleTitular = new javax.swing.JLabel();
        pnlAccountNumber = new ComponentRoundJilmar.PanelRound();
        txtAccountNumber = new javax.swing.JTextField();
        lblTitleAccountNumber = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlNumber = new ComponentRoundJilmar.PanelRound();
        txtNumber = new javax.swing.JTextField();
        lblTitleNumber = new javax.swing.JLabel();
        pnlNameReference = new ComponentRoundJilmar.PanelRound();
        txtNameReference = new javax.swing.JTextField();
        lblTitleNameReference = new javax.swing.JLabel();
        cmbAccount = new javax.swing.JComboBox<>();
        lblTitleAccounType = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox<>();
        lblTitleCity = new javax.swing.JLabel();
        cmbProvince = new javax.swing.JComboBox<>();
        lblTitleProvince = new javax.swing.JLabel();
        pnlNacionality = new ComponentRoundJilmar.PanelRound();
        txtNacionality = new javax.swing.JTextField();
        lblTitleNacionality = new javax.swing.JLabel();
        pnlEmail = new ComponentRoundJilmar.PanelRound();
        txtEmail = new javax.swing.JTextField();
        lblTitleEmail = new javax.swing.JLabel();
        cmbOccupation = new javax.swing.JComboBox<>();
        lblTitleOcuppation = new javax.swing.JLabel();
        pnlAddress = new ComponentRoundJilmar.PanelRound();
        txtAddress = new javax.swing.JTextField();
        lblTitleAddress = new javax.swing.JLabel();
        pnlPhone = new ComponentRoundJilmar.PanelRound();
        txtPhone = new javax.swing.JTextField();
        lblTitlePhone = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        lblTitleStatus = new javax.swing.JLabel();
        lblTitleBirthDate = new javax.swing.JLabel();
        pnlCode = new ComponentRoundJilmar.PanelRound();
        txtCode = new javax.swing.JTextField();
        lblTitleCode = new javax.swing.JLabel();
        pnlIdentification = new ComponentRoundJilmar.PanelRound();
        txtIdentification = new javax.swing.JTextField();
        lblTitleIdentification = new javax.swing.JLabel();
        pnlLastName = new ComponentRoundJilmar.PanelRound();
        txtLastName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblTitleLastName = new javax.swing.JLabel();
        pnlName = new ComponentRoundJilmar.PanelRound();
        txtName = new javax.swing.JTextField();
        lblTitleName = new javax.swing.JLabel();
        lblTitleUpdata = new javax.swing.JLabel();
        lblFocus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelActions.setBackground(new java.awt.Color(0, 0, 0));
        PanelActions.setPreferredSize(new java.awt.Dimension(1220, 30));
        PanelActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(PanelActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelWallpaper.setPreferredSize(new java.awt.Dimension(1220, 670));
        PanelWallpaper.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(131, 65, 255));
        btnDelete.setRoundBottomLeft(20);
        btnDelete.setRoundBottomRight(20);
        btnDelete.setRoundTopLeft(20);
        btnDelete.setRoundTopRight(20);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });

        lblDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDelete.setForeground(new java.awt.Color(255, 255, 255));
        lblDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDelete.setText("Eliminar");
        lblDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDeleteMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnDeleteLayout = new javax.swing.GroupLayout(btnDelete);
        btnDelete.setLayout(btnDeleteLayout);
        btnDeleteLayout.setHorizontalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDeleteLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnDeleteLayout.setVerticalGroup(
            btnDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDeleteLayout.createSequentialGroup()
                .addComponent(lblDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        PanelWallpaper.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 620, 120, 30));

        pnlBirthDate.setBackground(new java.awt.Color(255, 255, 255));
        pnlBirthDate.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlBirthDate.setRoundBottomLeft(20);
        pnlBirthDate.setRoundBottomRight(20);
        pnlBirthDate.setRoundTopLeft(20);
        pnlBirthDate.setRoundTopRight(20);

        txtBirthDate.setBorder(null);

        javax.swing.GroupLayout pnlBirthDateLayout = new javax.swing.GroupLayout(pnlBirthDate);
        pnlBirthDate.setLayout(pnlBirthDateLayout);
        pnlBirthDateLayout.setHorizontalGroup(
            pnlBirthDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBirthDateLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlBirthDateLayout.setVerticalGroup(
            pnlBirthDateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBirthDateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBirthDate, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 360, 40));

        pnlSearch.setBackground(new java.awt.Color(255, 255, 255));
        pnlSearch.setRoundBottomLeft(20);
        pnlSearch.setRoundBottomRight(20);
        pnlSearch.setRoundTopLeft(20);
        pnlSearch.setRoundTopRight(20);
        pnlSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSetData.setBackground(new java.awt.Color(131, 65, 255));
        btnSetData.setRoundBottomLeft(20);
        btnSetData.setRoundBottomRight(20);
        btnSetData.setRoundTopLeft(20);
        btnSetData.setRoundTopRight(20);
        btnSetData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSetDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSetDataMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Establecer Datos");

        javax.swing.GroupLayout btnSetDataLayout = new javax.swing.GroupLayout(btnSetData);
        btnSetData.setLayout(btnSetDataLayout);
        btnSetDataLayout.setHorizontalGroup(
            btnSetDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSetDataLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        btnSetDataLayout.setVerticalGroup(
            btnSetDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSetDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pnlSearch.add(btnSetData, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 120, 30));

        lblTitle.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lblTitle.setText("Buscar Cliente por cédula");
        pnlSearch.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnSearch.setBackground(new java.awt.Color(131, 65, 255));
        btnSearch.setRoundBottomLeft(20);
        btnSearch.setRoundBottomRight(20);
        btnSearch.setRoundTopLeft(20);
        btnSearch.setRoundTopRight(20);
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnSearchLayout = new javax.swing.GroupLayout(btnSearch);
        btnSearch.setLayout(btnSearchLayout);
        btnSearchLayout.setHorizontalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSearchLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );
        btnSearchLayout.setVerticalGroup(
            btnSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlSearch.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, 30));

        PanelWallpaper.add(pnlSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 380, 50));

        btnUpdata.setBackground(new java.awt.Color(131, 65, 255));
        btnUpdata.setRoundBottomLeft(20);
        btnUpdata.setRoundBottomRight(20);
        btnUpdata.setRoundTopLeft(20);
        btnUpdata.setRoundTopRight(20);
        btnUpdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdataMouseExited(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Actualizar");
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel42MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout btnUpdataLayout = new javax.swing.GroupLayout(btnUpdata);
        btnUpdata.setLayout(btnUpdataLayout);
        btnUpdataLayout.setHorizontalGroup(
            btnUpdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdataLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel42)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnUpdataLayout.setVerticalGroup(
            btnUpdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdataLayout.createSequentialGroup()
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        PanelWallpaper.add(btnUpdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 620, 120, 30));

        pnlBalance.setBackground(new java.awt.Color(255, 255, 255));
        pnlBalance.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlBalance.setRoundBottomLeft(20);
        pnlBalance.setRoundBottomRight(20);
        pnlBalance.setRoundTopLeft(20);
        pnlBalance.setRoundTopRight(20);

        txtBalance.setBorder(null);

        javax.swing.GroupLayout pnlBalanceLayout = new javax.swing.GroupLayout(pnlBalance);
        pnlBalance.setLayout(pnlBalanceLayout);
        pnlBalanceLayout.setHorizontalGroup(
            pnlBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlBalanceLayout.setVerticalGroup(
            pnlBalanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBalanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 560, 170, 40));

        lblTitleBalance.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleBalance.setText("Saldo:");
        PanelWallpaper.add(lblTitleBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 540, -1, -1));

        pnlPin.setBackground(new java.awt.Color(255, 255, 255));
        pnlPin.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlPin.setRoundBottomLeft(20);
        pnlPin.setRoundBottomRight(20);
        pnlPin.setRoundTopLeft(20);
        pnlPin.setRoundTopRight(20);

        txtPIN.setBorder(null);

        javax.swing.GroupLayout pnlPinLayout = new javax.swing.GroupLayout(pnlPin);
        pnlPin.setLayout(pnlPinLayout);
        pnlPinLayout.setHorizontalGroup(
            pnlPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPinLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlPinLayout.setVerticalGroup(
            pnlPinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPIN, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 170, 40));

        lblTitlePin.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitlePin.setText("PIN:");
        PanelWallpaper.add(lblTitlePin, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, -1, -1));

        pnlPassword.setBackground(new java.awt.Color(255, 255, 255));
        pnlPassword.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlPassword.setRoundBottomLeft(20);
        pnlPassword.setRoundBottomRight(20);
        pnlPassword.setRoundTopLeft(20);
        pnlPassword.setRoundTopRight(20);

        txtPassword.setBorder(null);

        javax.swing.GroupLayout pnlPasswordLayout = new javax.swing.GroupLayout(pnlPassword);
        pnlPassword.setLayout(pnlPasswordLayout);
        pnlPasswordLayout.setHorizontalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        pnlPasswordLayout.setVerticalGroup(
            pnlPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 170, 40));

        lblTitlePassword.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitlePassword.setText("Contraseña:");
        PanelWallpaper.add(lblTitlePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, -1, -1));

        pnlUser.setBackground(new java.awt.Color(255, 255, 255));
        pnlUser.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlUser.setRoundBottomLeft(20);
        pnlUser.setRoundBottomRight(20);
        pnlUser.setRoundTopLeft(20);
        pnlUser.setRoundTopRight(20);

        txtUser.setBorder(null);

        javax.swing.GroupLayout pnlUserLayout = new javax.swing.GroupLayout(pnlUser);
        pnlUser.setLayout(pnlUserLayout);
        pnlUserLayout.setHorizontalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUserLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlUserLayout.setVerticalGroup(
            pnlUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 170, 40));

        lblTitleUser.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleUser.setText("Usuario:");
        PanelWallpaper.add(lblTitleUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, -1, -1));

        pnlTitular.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitular.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlTitular.setRoundBottomLeft(20);
        pnlTitular.setRoundBottomRight(20);
        pnlTitular.setRoundTopLeft(20);
        pnlTitular.setRoundTopRight(20);

        txtTitular.setBorder(null);

        javax.swing.GroupLayout pnlTitularLayout = new javax.swing.GroupLayout(pnlTitular);
        pnlTitular.setLayout(pnlTitularLayout);
        pnlTitularLayout.setHorizontalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTitularLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        pnlTitularLayout.setVerticalGroup(
            pnlTitularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTitularLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitular, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 420, 360, 40));

        lblTitleTitular.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleTitular.setText("Titular:");
        PanelWallpaper.add(lblTitleTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, -1, -1));

        pnlAccountNumber.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccountNumber.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlAccountNumber.setRoundBottomLeft(20);
        pnlAccountNumber.setRoundBottomRight(20);
        pnlAccountNumber.setRoundTopLeft(20);
        pnlAccountNumber.setRoundTopRight(20);

        txtAccountNumber.setBorder(null);

        javax.swing.GroupLayout pnlAccountNumberLayout = new javax.swing.GroupLayout(pnlAccountNumber);
        pnlAccountNumber.setLayout(pnlAccountNumberLayout);
        pnlAccountNumberLayout.setHorizontalGroup(
            pnlAccountNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAccountNumberLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(txtAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlAccountNumberLayout.setVerticalGroup(
            pnlAccountNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAccountNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, 360, 40));

        lblTitleAccountNumber.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleAccountNumber.setText("Número de Cuenta:");
        PanelWallpaper.add(lblTitleAccountNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, -1, -1));

        jLabel29.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel29.setText("Datos de la Cuenta");
        PanelWallpaper.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, -1, -1));

        pnlNumber.setBackground(new java.awt.Color(255, 255, 255));
        pnlNumber.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlNumber.setRoundBottomLeft(20);
        pnlNumber.setRoundBottomRight(20);
        pnlNumber.setRoundTopLeft(20);
        pnlNumber.setRoundTopRight(20);

        txtNumber.setBorder(null);

        javax.swing.GroupLayout pnlNumberLayout = new javax.swing.GroupLayout(pnlNumber);
        pnlNumber.setLayout(pnlNumberLayout);
        pnlNumberLayout.setHorizontalGroup(
            pnlNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNumberLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        pnlNumberLayout.setVerticalGroup(
            pnlNumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 360, 40));

        lblTitleNumber.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleNumber.setText("Número de Teléfono:");
        PanelWallpaper.add(lblTitleNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, -1));

        pnlNameReference.setBackground(new java.awt.Color(255, 255, 255));
        pnlNameReference.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlNameReference.setRoundBottomLeft(20);
        pnlNameReference.setRoundBottomRight(20);
        pnlNameReference.setRoundTopLeft(20);
        pnlNameReference.setRoundTopRight(20);

        txtNameReference.setBorder(null);

        javax.swing.GroupLayout pnlNameReferenceLayout = new javax.swing.GroupLayout(pnlNameReference);
        pnlNameReference.setLayout(pnlNameReferenceLayout);
        pnlNameReferenceLayout.setHorizontalGroup(
            pnlNameReferenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameReferenceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtNameReference, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlNameReferenceLayout.setVerticalGroup(
            pnlNameReferenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNameReferenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNameReference, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlNameReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 360, 40));

        lblTitleNameReference.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleNameReference.setText("Nombre de Referencia:");
        PanelWallpaper.add(lblTitleNameReference, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, -1, -1));

        cmbAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Cuenta de Ahorros", "Cuenta Corriente" }));
        cmbAccount.setBorder(null);
        cmbAccount.setPreferredSize(new java.awt.Dimension(350, 30));
        cmbAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAccountActionPerformed(evt);
            }
        });
        PanelWallpaper.add(cmbAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, -1, -1));

        lblTitleAccounType.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleAccounType.setText("Tipo de Cuenta");
        PanelWallpaper.add(lblTitleAccounType, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, -1, -1));

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "" }));
        cmbCity.setBorder(null);
        cmbCity.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelWallpaper.add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, 160, 40));

        lblTitleCity.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleCity.setText("Ciudad");
        PanelWallpaper.add(lblTitleCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        cmbProvince.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", " " }));
        cmbProvince.setBorder(null);
        cmbProvince.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelWallpaper.add(cmbProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 160, 40));

        lblTitleProvince.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleProvince.setText("Provincia");
        PanelWallpaper.add(lblTitleProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        pnlNacionality.setBackground(new java.awt.Color(255, 255, 255));
        pnlNacionality.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlNacionality.setRoundBottomLeft(20);
        pnlNacionality.setRoundBottomRight(20);
        pnlNacionality.setRoundTopLeft(20);
        pnlNacionality.setRoundTopRight(20);

        txtNacionality.setBorder(null);
        txtNacionality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNacionalityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNacionalityLayout = new javax.swing.GroupLayout(pnlNacionality);
        pnlNacionality.setLayout(pnlNacionalityLayout);
        pnlNacionalityLayout.setHorizontalGroup(
            pnlNacionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacionalityLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(txtNacionality, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlNacionalityLayout.setVerticalGroup(
            pnlNacionalityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNacionalityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNacionality, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlNacionality, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 360, 40));

        lblTitleNacionality.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleNacionality.setText("Nacionalidad:");
        PanelWallpaper.add(lblTitleNacionality, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, -1));

        pnlEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmail.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlEmail.setRoundBottomLeft(20);
        pnlEmail.setRoundBottomRight(20);
        pnlEmail.setRoundTopLeft(20);
        pnlEmail.setRoundTopRight(20);

        txtEmail.setBorder(null);

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 360, 40));

        lblTitleEmail.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleEmail.setText("Correo Electrónico:");
        PanelWallpaper.add(lblTitleEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, -1));

        cmbOccupation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Estudiante", "Maestro(a) / Profesor(a)", "Médico(a)", "Ingeniero(a)", "Abogado(a)", "Arquitecto(a)", "Contador(a)", "Empresario(a)", "Artista", "Músico(a)", "Actor / Actriz", "Escritor(a)", "Fotógrafo(a)", "Diseñador(a) gráfico(a)", "Programador(a)", "Chef / Cocinero(a)", "Agricultor(a)", "Artesano(a)", "Jardinero(a)", "Peluquero(a) / Estilista", "Bombero(a)", "Policía", "Paramédico(a)", "Enfermero(a)", "Psicólogo(a)", "Terapeuta", "Consultor(a)", "Investigador(a)", "Veterinario(a)", "Voluntario(a)" }));
        cmbOccupation.setBorder(null);
        cmbOccupation.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelWallpaper.add(cmbOccupation, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 360, 30));

        lblTitleOcuppation.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleOcuppation.setText("Ocupación:");
        PanelWallpaper.add(lblTitleOcuppation, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, -1, -1));

        pnlAddress.setBackground(new java.awt.Color(255, 255, 255));
        pnlAddress.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlAddress.setRoundBottomLeft(20);
        pnlAddress.setRoundBottomRight(20);
        pnlAddress.setRoundTopLeft(20);
        pnlAddress.setRoundTopRight(20);

        txtAddress.setBorder(null);

        javax.swing.GroupLayout pnlAddressLayout = new javax.swing.GroupLayout(pnlAddress);
        pnlAddress.setLayout(pnlAddressLayout);
        pnlAddressLayout.setHorizontalGroup(
            pnlAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlAddressLayout.setVerticalGroup(
            pnlAddressLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddressLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 360, 40));

        lblTitleAddress.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleAddress.setText("Dirección:");
        PanelWallpaper.add(lblTitleAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        pnlPhone.setBackground(new java.awt.Color(255, 255, 255));
        pnlPhone.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlPhone.setRoundBottomLeft(20);
        pnlPhone.setRoundBottomRight(20);
        pnlPhone.setRoundTopLeft(20);
        pnlPhone.setRoundTopRight(20);

        txtPhone.setBorder(null);

        javax.swing.GroupLayout pnlPhoneLayout = new javax.swing.GroupLayout(pnlPhone);
        pnlPhone.setLayout(pnlPhoneLayout);
        pnlPhoneLayout.setHorizontalGroup(
            pnlPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlPhoneLayout.setVerticalGroup(
            pnlPhoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhoneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPhone, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 360, 40));

        lblTitlePhone.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitlePhone.setText("Telefono:");
        PanelWallpaper.add(lblTitlePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Soltero/a", "Casado/a", "Divorciado/a", "Viudo/a" }));
        cmbStatus.setPreferredSize(new java.awt.Dimension(350, 30));
        PanelWallpaper.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, -1, -1));

        lblTitleStatus.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleStatus.setText("Estado Civil:");
        PanelWallpaper.add(lblTitleStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        lblTitleBirthDate.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleBirthDate.setText("Fecha de Nacimiento:");
        PanelWallpaper.add(lblTitleBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        pnlCode.setBackground(new java.awt.Color(255, 255, 255));
        pnlCode.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlCode.setRoundBottomLeft(20);
        pnlCode.setRoundBottomRight(20);
        pnlCode.setRoundTopLeft(20);
        pnlCode.setRoundTopRight(20);

        txtCode.setBorder(null);

        javax.swing.GroupLayout pnlCodeLayout = new javax.swing.GroupLayout(pnlCode);
        pnlCode.setLayout(pnlCodeLayout);
        pnlCodeLayout.setHorizontalGroup(
            pnlCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodeLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlCodeLayout.setVerticalGroup(
            pnlCodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCode, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 360, 40));

        lblTitleCode.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleCode.setText("Codigo Dactilar:");
        PanelWallpaper.add(lblTitleCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        pnlIdentification.setBackground(new java.awt.Color(255, 255, 255));
        pnlIdentification.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlIdentification.setRoundBottomLeft(20);
        pnlIdentification.setRoundBottomRight(20);
        pnlIdentification.setRoundTopLeft(20);
        pnlIdentification.setRoundTopRight(20);

        txtIdentification.setBorder(null);

        javax.swing.GroupLayout pnlIdentificationLayout = new javax.swing.GroupLayout(pnlIdentification);
        pnlIdentification.setLayout(pnlIdentificationLayout);
        pnlIdentificationLayout.setHorizontalGroup(
            pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificationLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtIdentification, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlIdentificationLayout.setVerticalGroup(
            pnlIdentificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdentification, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 360, 40));

        lblTitleIdentification.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleIdentification.setText("Cédula de Identidad:");
        PanelWallpaper.add(lblTitleIdentification, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        pnlLastName.setBackground(new java.awt.Color(255, 255, 255));
        pnlLastName.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlLastName.setRoundBottomLeft(20);
        pnlLastName.setRoundBottomRight(20);
        pnlLastName.setRoundTopLeft(20);
        pnlLastName.setRoundTopRight(20);

        txtLastName.setBorder(null);

        javax.swing.GroupLayout pnlLastNameLayout = new javax.swing.GroupLayout(pnlLastName);
        pnlLastName.setLayout(pnlLastNameLayout);
        pnlLastNameLayout.setHorizontalGroup(
            pnlLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLastNameLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLastNameLayout.setVerticalGroup(
            pnlLastNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLastNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 360, 40));
        PanelWallpaper.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblTitleLastName.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleLastName.setText("Apellidos:");
        PanelWallpaper.add(lblTitleLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        pnlName.setBackground(new java.awt.Color(255, 255, 255));
        pnlName.setPreferredSize(new java.awt.Dimension(350, 30));
        pnlName.setRoundBottomLeft(20);
        pnlName.setRoundBottomRight(20);
        pnlName.setRoundTopLeft(20);
        pnlName.setRoundTopRight(20);

        txtName.setBorder(null);

        javax.swing.GroupLayout pnlNameLayout = new javax.swing.GroupLayout(pnlName);
        pnlName.setLayout(pnlNameLayout);
        pnlNameLayout.setHorizontalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlNameLayout.setVerticalGroup(
            pnlNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelWallpaper.add(pnlName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 40));

        lblTitleName.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblTitleName.setText("Nombres:");
        PanelWallpaper.add(lblTitleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblTitleUpdata.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblTitleUpdata.setText("Modificación de Datos del Cliente");
        PanelWallpaper.add(lblTitleUpdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblFocus.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblFocus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/p3tarea3grupo3/image/registerFocus.png"))); // NOI18N
        PanelWallpaper.add(lblFocus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(PanelWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAccountActionPerformed

    private void btnUpdataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdataMouseEntered
        // TODO add your handling code here:
        btnUpdata.setBackground(new Color(65,78,125));
        btnUpdata.repaint();
    }//GEN-LAST:event_btnUpdataMouseEntered

    private void btnUpdataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdataMouseExited
        // TODO add your handling code here
        btnUpdata.setBackground(new Color(131,65,255));
        btnUpdata.repaint();
    }//GEN-LAST:event_btnUpdataMouseExited

    private void txtNacionalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNacionalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNacionalityActionPerformed

    private void jLabel42MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42MouseEntered

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       
    }//GEN-LAST:event_jLabel1MouseEntered

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
       btnSearch.setBackground(new Color(65,78,125));
        btnSearch.repaint();
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        btnSearch.setBackground(new Color(131,65,255));
        btnSearch.repaint();
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnSetDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetDataMouseEntered
        btnSetData.setBackground(new Color(65,78,125));
        btnSetData.repaint();
    }//GEN-LAST:event_btnSetDataMouseEntered

    private void btnSetDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetDataMouseExited
        btnSetData.setBackground(new Color(131,65,255));
        btnSetData.repaint();
    }//GEN-LAST:event_btnSetDataMouseExited

    private void lblDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteMouseEntered

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(new Color(65,78,125));
        btnDelete.repaint();
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(131,65,255));
        btnDelete.repaint();
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnSetDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetDataMouseClicked
        if(btnSetData.isEnabled()){
            setData();
            btnUpdata.setEnabled(true);
            btnDelete.setEnabled(true);
        }
        btnSetData.setEnabled(false);
    }//GEN-LAST:event_btnSetDataMouseClicked

    private void btnUpdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdataMouseClicked
        SearchClient search = new SearchClient();
        search.setVisible(true);
        btnSetData.setEnabled(true);  
    }//GEN-LAST:event_btnUpdataMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

        if (!txtIdentification.getText().isEmpty()) {
            Document documentToDelete = new Document("identification", Long.parseLong(txtIdentification.getText()));
            DeleteMongo deleteMongo = new DeleteMongo();
            deleteMongo.deleteDocument(documentToDelete);
            cleanRecord();
            btnDelete.setEnabled(false);
    }
        
    }//GEN-LAST:event_btnDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdataData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdataData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdataData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdataData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdataData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelActions;
    private javax.swing.JPanel PanelWallpaper;
    private ComponentRoundJilmar.PanelRound btnDelete;
    private ComponentRoundJilmar.PanelRound btnSearch;
    private ComponentRoundJilmar.PanelRound btnSetData;
    private ComponentRoundJilmar.PanelRound btnUpdata;
    private javax.swing.JComboBox<String> cmbAccount;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbOccupation;
    private javax.swing.JComboBox<String> cmbProvince;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDelete;
    private javax.swing.JLabel lblFocus;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleAccounType;
    private javax.swing.JLabel lblTitleAccountNumber;
    private javax.swing.JLabel lblTitleAddress;
    private javax.swing.JLabel lblTitleBalance;
    private javax.swing.JLabel lblTitleBirthDate;
    private javax.swing.JLabel lblTitleCity;
    private javax.swing.JLabel lblTitleCode;
    private javax.swing.JLabel lblTitleEmail;
    private javax.swing.JLabel lblTitleIdentification;
    private javax.swing.JLabel lblTitleLastName;
    private javax.swing.JLabel lblTitleNacionality;
    private javax.swing.JLabel lblTitleName;
    private javax.swing.JLabel lblTitleNameReference;
    private javax.swing.JLabel lblTitleNumber;
    private javax.swing.JLabel lblTitleOcuppation;
    private javax.swing.JLabel lblTitlePassword;
    private javax.swing.JLabel lblTitlePhone;
    private javax.swing.JLabel lblTitlePin;
    private javax.swing.JLabel lblTitleProvince;
    private javax.swing.JLabel lblTitleStatus;
    private javax.swing.JLabel lblTitleTitular;
    private javax.swing.JLabel lblTitleUpdata;
    private javax.swing.JLabel lblTitleUser;
    private ComponentRoundJilmar.PanelRound pnlAccountNumber;
    private ComponentRoundJilmar.PanelRound pnlAddress;
    private ComponentRoundJilmar.PanelRound pnlBalance;
    private ComponentRoundJilmar.PanelRound pnlBirthDate;
    private ComponentRoundJilmar.PanelRound pnlCode;
    private ComponentRoundJilmar.PanelRound pnlEmail;
    private ComponentRoundJilmar.PanelRound pnlIdentification;
    private ComponentRoundJilmar.PanelRound pnlLastName;
    private ComponentRoundJilmar.PanelRound pnlNacionality;
    private ComponentRoundJilmar.PanelRound pnlName;
    private ComponentRoundJilmar.PanelRound pnlNameReference;
    private ComponentRoundJilmar.PanelRound pnlNumber;
    private ComponentRoundJilmar.PanelRound pnlPassword;
    private ComponentRoundJilmar.PanelRound pnlPhone;
    private ComponentRoundJilmar.PanelRound pnlPin;
    private ComponentRoundJilmar.PanelRound pnlSearch;
    private ComponentRoundJilmar.PanelRound pnlTitular;
    private ComponentRoundJilmar.PanelRound pnlUser;
    private javax.swing.JTextField txtAccountNumber;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdentification;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtNacionality;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNameReference;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPIN;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtTitular;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
 
    private void setData(){
        SearchData data = queryJson();
        ListClient listClient = ListClient.getInstance();
        List<Account> listAccounts = listClient.getAccount();
        for (Account acc : listAccounts) {
            if (acc.getId()== data.getIdentification()) {
            txtName.setText(acc.getClient().getName());
            txtLastName.setText(acc.getClient().getLastName());
            txtIdentification.setText(acc.getClient().getIdentification());
            txtCode.setText(acc.getClient().getCode());
            txtBirthDate.setText(acc.getClient().getBirthDate());
            cmbStatus.setSelectedIndex(comboBox(cmbStatus, acc.getClient().getStatus()));
            txtPhone.setText(String.valueOf(acc.getClient().getPhone()));
            txtAddress.setText(acc.getClient().getAddress());
            cmbOccupation.setSelectedIndex(comboBox(cmbOccupation, acc.getClient().getOccupation()));
            txtEmail.setText(acc.getClient().getEmail());
            txtNacionality.setText(acc.getClient().getNationality());
            cmbProvince.setSelectedIndex(comboBox(cmbProvince, acc.getClient().getProvince()));
            cmbCity.setSelectedIndex(comboBox(cmbCity, acc.getClient().getCity()));
            txtNameReference.setText(acc.getClient().getReferenceName());
            txtNumber.setText(String.valueOf(acc.getClient().getReferencePhone()));
            txtAccountNumber.setText(acc.getAccountNumber());
            txtTitular.setText(acc.getTitular());
            txtUser.setText(acc.getUser());
            txtPassword.setText(acc.getPassword());
            txtPIN.setText(acc.getPin());
            txtBalance.setText(Double.toString(acc.getBalance()));
            
            break;
            }
        }
        cleanRecord();
    }
    
    private void updateData(){
        SearchData data = queryJson();             
        String name = txtName.getText();
        String lastName = txtLastName.getText();
        long identification = Long.parseLong(txtIdentification.getText());
        String code =txtCode.getText();
        String birthDate = txtBirthDate.getText();
        String Status = String.valueOf(cmbStatus.getSelectedItem());
        long phone = Long.parseLong(txtPhone.getText());
        String Address = txtAddress.getText();
        String Occupation = String.valueOf(cmbOccupation.getSelectedItem());
        String email = txtEmail.getText();
        String nacionality = txtNacionality.getText();
        String Province = String.valueOf(cmbProvince.getSelectedItem());
        String city = String.valueOf(cmbCity.getSelectedItem());
        String nameReference = txtNameReference.getText();
        Long number = Long.parseLong(txtNumber.getText());
        String accountNumber = txtAccountNumber.getText();
        String titular = txtTitular.getText();
        String user = txtUser.getText();
        String password = txtPassword.getText();
        String PIN = txtPIN.getText();
        String Balance = txtBalance.getText();


       
    }
    private void cleanRecord(){
        txtName.setText(" ");
        txtLastName.setText(" ");
        txtIdentification.setText("");
        txtCode.setText("");
        txtBirthDate.setText("");
        cmbStatus.setSelectedIndex(0);
        txtPhone.setText("");
        txtAddress.setText("");
        cmbOccupation.setSelectedIndex(0);
        txtEmail.setText("");
        txtNacionality.setText("");
        cmbProvince.setSelectedIndex(0);
        cmbCity.setSelectedIndex(0);
        txtNameReference.setText("");
        txtNumber.setText("");
        txtAccountNumber.setText("");
        txtTitular.setText("");
        txtUser.setText("");
        txtPassword.setText("");
        txtPIN.setText("");
        txtBalance.setText(" ");
    }

    private SearchData queryJson(){
        SearchData search = new SearchData();
        return search.readFileJson();
    }
    public int comboBox(JComboBox cmb, String value) {
        for (int i = 0; i < cmb.getItemCount(); i++) {
            String v = (String) cmb.getItemAt(i);
            if(v.equals(value)){
                return i;
            }else if(v.contains(value)) {
                return i;
            }
        }
        return 0;
    }
}
